version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: google-auth
    versions:
    - 1.24.0
    - 1.25.0
    - 1.26.0
    - 1.26.1
    - 1.27.0
    - 1.27.1
    - 1.28.0
    - 1.28.1
    - 1.29.0
  - dependency-name: google-api-python-client
    versions:
    - 1.12.8
    - 2.0.2
    - 2.1.0
    - 2.2.0
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.1
    - 1.36.2
    - 1.37.0
    - 1.37.1
  - dependency-name: google-api-core
    versions:
    - 1.25.1
    - 1.26.0
    - 1.26.1
    - 1.26.2
  - dependency-name: google-auth-oauthlib
    versions:
    - 0.4.2
    - 0.4.3
  - dependency-name: grpcio
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: gitpython
    versions:
    - 3.1.12
    - 3.1.13
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: urllib3
    versions:
    - 1.26.3
